#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := morse_code

ESPTOOL_PORT := "/dec/cu.SLAB_USBtoUART"
ESPTOOL_FF := "80m"
ESPTOOL_FS := "4m"

include $(IDF_PATH)/make/project.mk

